<?php

namespace Effectra\Contracts\Http;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

/**
 * Represents the Router Interface.
 */
interface RouterInterface
{
    /**
     * Dispatches the server request and returns the response.
     *
     * @param ServerRequestInterface $request The server request to dispatch.
     * @return ResponseInterface The response generated by the dispatch process.
     */
    public function dispatch(ServerRequestInterface $request): ResponseInterface;
}
